### PR TITLE
addMaterial

### PR DESCRIPTION
**Pull request by xasopheno**
You can now and a material and then it's listed.

### CODE REVIEW

**Comment by lpender** [comment]
It makes sense that you branched off of your previous branch in this case, because that branch was blocking any future work. Just keep in mind, normally you branch off of master. 

Branching off of a branch is a bit more difficult to code review, because you end up reviewing the changes from both branches (until the first one is merged).

Also, if you end up making changes to the first branch/pull request, then you have to rebase that into this branch and resolve any conflicts before continuing.

**Comment by lpender** [comment]
I think we might need to do some of this together...

**Comment by lpender** [comment]
Will you give me a ring when you're next working on this?

**Comment by lpender** [comment]
The commit message should have a format something along the lines of:


```
Summarize of the changes made in 50 characters or less.

- Bullet points about what changed.
- Or why it needed to be changed.
```

It gets a bit more detailed than this even. I'd suggest reading: http://chris.beams.io/posts/git-commit/

**Comment by lpender** [comment]
A more descriptive title for the Pull Request would be helpful as well. Something along the lines of:

"User Adds Material"

**Comment by lpender** [comment]
Let's merge the first one together ey?

**Comment by xasopheno** [comment]
Hey! I'm just getting to this now. Sounds great. Perhaps we could do it
remote tomorrow? I'm also around tonight for another couple hours.

The next thing I'm doing is making the material editable. Little stuck.
Maybe we can go over that, too.

Thanks again, D

Danny Meyer
We can do great things if we do them together.
US +1 (970)-420-7526
Skype: xasopheno
www.ThisIsAmazing.org
<http://www.thisisamazing.org/>www.TheDJMLC.com <http://www.thedjmlc.com/>

**Pull request merged**
